### ISSUE TITLE
interpreting output

### ISSUE THREAD

**Issue by kabylkas** [ehab-abdelhamid/GraMi#10]
Hi, 
This is not really an issue... more of a question... I would really appreciate if you could briefly respond.

Could you please explain how to interpret the output.txt? I ran grami on test2.lg:
`./grami -f test2.lg -s 3 -t 1 -p 0`
what I got was this:
```
0.073
3
0:
v 0 1
v 1 2
v 2 3
e 0 1 5
e 1 2 6
1:
v 0 1
v 1 2
e 0 1 5
2:
v 0 2
v 1 3
e 0 1 6

```
Could you please briefly explain what each value means? For example, I am not sure what is "v 0 2". There was no such node in the graph...

Thank you.

**Comment by Speed2Market** [comment]
A picture is helpful, thanks to [Pajek](http://mrvar.fdv.uni-lj.si/pajek/)

![test2a](https://user-images.githubusercontent.com/36772378/36609446-af83dcb2-1881-11e8-8dec-18c9118683ba.jpg)

And I would interpret the output as follows, where the indices are used internally by the GraMi code:

<pre><code>
0.073	 <- Run time in seconds.
3	 <- Number of frequent subgraphs
0:	<- Frequent Subgraph #0
v 0 1	<- Vertex index 0 label 1
v 1 2	<- Vertex index 1 label 2
v 2 3       <- Vertex index 2 label 3
e 0 1 5     <- edge from index 0 to index 1 edgeLabel 5 (V. Label 1 to V. Label 2)
e 1 2 6     <- edge from index 1 to index 2 edgeLabel 6 (V. Label 2 to V. Label 3
1:          <- Frequent Subgraph #1
v 0 1       <- Vertex index 0 label 1
v 1 2       <- Vertex index 1 label 2
e 0 1 5     <- edge from index 0 to index 1 edgeLabel 5 (V. Label 1 to V. Label 2)
2:          <- Frequent Subgraph #2
v 0 2       <- Vertex index 0 label 2
v 1 3       <- Vertex index 1 label 3
e 0 1 6     <- edge from index 0 to index 1 edgeLabel 6 (V. Label 2 to V. Label 3)
 </code></pre>
