### ISSUE TITLE
Approximate mining

### ISSUE THREAD

**Issue by MeriemBouzbila** [ehab-abdelhamid/GraMi#11]
This is a question not an issue. I run GraMi to mine frequent subgraphs in undirected graph and I always run out of memory, so I thought of using approximate mining. However, I do not understand quite well the command in the example:
Find frequent subgraphs in the "mico" undirected graph, with minimum frequency = 14000 and approximation: ./grami -f mico.lg -s 9340 -t 0 -p 0 -approxA 0.0002 -approxB=0
if minimum frequency = 14000 then why -s 9340 and not -s 14000? 
approxA 0.0002 isn't that very low? a good approximation will have alpha close to 1, something like 0.7 or 0.8, right?

**Comment by ehab-abdelhamid** [comment]
- Yes, this is a mistake; it should be -s 14000 for a frequency=14000.
- regarding approxA, as mentioned in the paper: if it is set to 1, then there is no approximation. I suggest you test using different approxA values, start with a very low value and increase it gradually until you get results within reasonable time and good accuracy.

**Comment by MeriemBouzbila** [comment]
This is clear. Thank you Ehab
