### ISSUE TITLE
Readme.txt examples don't work 'Error: Could not find or load main class Dijkstra.main'

### ISSUE THREAD

**Issue by Manslow** [ehab-abdelhamid/GraMi#7]
I followed the readme.txt and tried to run the examples. None of them worked due to 'Error: Could not find or load main class Dijkstra.main'. I can see that the main files are there but I suppose they are not being referenced correctly by grami executable?

```
Genghis:GraMi-master user$ ./grami -f citeseer.lg -s 160 -t 1 -p 1 -d 200
Dataset: citeseer.lg
[DIRECTED]
Frequenct Pattern Mining, with minimum distance: 200
No constraints on labels
Minimum frequency: 160
Starting GraMi ...
Error: Could not find or load main class Dijkstra.main
GraMi Finished.
```

**Comment by ehab-abdelhamid** [comment]
Did you compile the source code and build the binaries? Did you get any errors while compiling?
