### ISSUE TITLE
Multiple labels per node/edge

### ISSUE THREAD

**Issue by kiyakutku** [ehab-abdelhamid/GraMi#8]
The proposed methods also support directed graphs and multiple labels per node/edge.  
Does this software support this feature? If not so, is it possible to patch it via software?
I would be appreciated if you had an idea on how to change the software..

Thank you.

**Comment by ehab-abdelhamid** [comment]
Theoritically, this can be done. But the current code does not support multiple node/edge labels. It needs some modifications to support that feature.
