### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by Kyeongpil** [ehab-abdelhamid/GraMi#9]
Hi,
I run code with my own graph which consist of 30K nodes(all labels are 1), and about 600K edges(most labels are different each other).

However, when I run the code about 5~6 hours, it occurs OutOfMemoryError exception.
This happens even I set the initial size of heap memory in JVM as 40GB .

Do you know why exception occurs and solutions?

**Comment by ehab-abdelhamid** [comment]
It could be that the number of generated frequent subgraphs is too huge, did you set the threshold to be too small?
